spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musinsa_monitor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: won9975744

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true









