spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musinsa_monitor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: [id]
    password: [pwd]

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LW11c2luc2EtbW9uaXRvci1wcm9qZWN0LWp3dC1zZWNyZXQK

jasypt:
  encryptor:
    bean: jasyptStringEncryptor










